steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'us-central1-docker.pkg.dev/nestjs-devops/nestjs-crud-app/production',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/nestjs-devops/nestjs-crud-app/production']