apiVersion: v1
kind: Service
metadata:
  namespace: nestjs-crud
  name: nestjs-crud-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
  